pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - author = dependabot[bot]
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: rebase
