#!/usr/bin/env ruby
# frozen_string_literal: true

require 'logger'
require 'netrc'
require 'octokit'
require 'pinboard'

require 'pinboard_fixup_github_titles'
include PinboardFixupGithubTitles

logger = Logger.new(STDERR)
logger.progname = File.basename(__FILE__)
desired_log_level = ENV.fetch('LOG_LEVEL', 'INFO')

begin
  logger.level = Logger::Severity.const_get(desired_log_level)
rescue NameError
  logger.level = Logger::Severity::WARN
  logger.warn("Error evaluating log level #{desired_log_level}. Using #{Logger::Severity.constants[logger.level]} instead.")
end

if pinboard_api_token = ENV['PINBOARD_API_TOKEN']
  pinboard = Pinboard::Client.new(token: pinboard_api_token)
  logger.info "Logged on to Pinboard as #{pinboard_api_token.split(':').first}"
else
  logger.error 'Pinboard API token missing.'
  exit 1
end

# Authentication is required due to Github's API rate limit
begin
  github = Octokit::Client.new(GithubCredentialsResolver.new.resolve)
rescue GithubCredentialsResolver::MissingCredentials => error
  logger.error error.message
  exit 2
end

if github.login
  logger.info "Logged on to github.com as #{github.user.login}"
else
  logger.error 'Login to github failed. Check your credentials.'
  exit 3
end

posts = pinboard.posts(meta: true)
logger.info "Processing #{posts.size} bookmarks"

stats = Stats.new
stats.gauge(:total, posts.size)

def page_title(url)
  Nokogiri::HTML(open(url)).at_css('h1.gh-header-title').text
end

def show_rate_limit(rate, logger)
  logger.info "rate limit: #{rate.limit}"
  logger.info "remaining: #{rate.remaining}"
  logger.info "resets_at: #{rate.resets_at}"
  logger.info "resets_in: #{rate.resets_in}"
end

show_rate_limit(github.rate_limit, logger)

# rubocop:disable Metrics/BlockLength
posts.each do |post|
  begin
    unless md = %r{//github.com/([^/]+/[^/]+)}.match(post.href)
      stats.increment(:not_applicable)
      next
    end

    repo = github.repo(md[1])

    if repo.description.nil? || repo.description.empty?
      stats.increment(:empty)
      logger.warn "#{repo.name}: Skipping because there is no description in the github repo."
      next
    end

    tags = post.tag
    tags << 'github' unless tags.include?('github')
    tags << 'pinboard-fixup-github-titles' unless tags.include?('pinboard-fixup-github-titles')
    tags << repo.language

    if %r{//github.com/([^/]+/[^/]+)/wiki}.match(post.href)
      canonical_description = "#{repo.name}: #{page_title(post.href)}"
      tags << 'wiki' unless tags.include?('wiki')
      stats.increment(:wiki)
     else
      canonical_description = "#{repo.name}: #{repo.description}"
    end

    if post.description == canonical_description
      stats.increment(:up_to_date)
      logger.info "#{repo.name}: Up to date"
      next
    end

    logger.info "#{repo.name}: Updating from '#{post.description}' to '#{canonical_description}'"

    pinboard.add(
      url: post.href,
      description: canonical_description,
      extended: post.extended,
      tags: tags,
      replace: 'yes',
      shared: post.shared ? post.shared : 'yes',
      toread: post.toread,
    )

    stats.increment(:updated)
  rescue => error
    stats.increment(:errors)
    logger.error "Could not handle #{post.href}: #{error.message}"
    show_rate_limit(github.rate_limit, logger)
  end
end

logger.info "Done: #{stats}"
