#!/usr/bin/env ruby
# frozen_string_literal: true

require 'erb'
require 'yaml'

`lpass sync`

YAML.safe_load(`lpass show pinboard-fixup-github-titles --notes`).each do |k, v|
  Object.const_set(k, v)
end

puts ERB.new(DATA.read).result

__END__
#!/bin/sh

docker run \
    --env GITHUB_LOGIN=<%= GITHUB_LOGIN %> \
    --env GITHUB_PASSWORD=<%= GITHUB_PASSWORD %> \
    --env PINBOARD_API_TOKEN=<%= PINBOARD_API_TOKEN %> \
    --name pinboard-fixup-github-titles \
  nerab/pinboard-fixup-github-titles:latest
